// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/bnb-chain/airdrop-service/internal/config"
	"github.com/bnb-chain/airdrop-service/internal/module/approval"
	"github.com/bnb-chain/airdrop-service/internal/module/http"
	"github.com/bnb-chain/airdrop-service/internal/wireset"
)

// Injectors from wire.go:

func Initialize(configPath string) (Application, error) {
	configConfig, err := config.NewConfig(configPath)
	if err != nil {
		return Application{}, err
	}
	logger, err := wireset.InitLogger(configConfig)
	if err != nil {
		return Application{}, err
	}
	keyManager, err := wireset.InitKeyManager(configConfig)
	if err != nil {
		return Application{}, err
	}
	store, err := wireset.InitStore(configConfig, logger)
	if err != nil {
		return Application{}, err
	}
	approvalService := approval.NewApprovalService(keyManager, store)
	httpServer := http.NewHttpServer(approvalService, logger)
	application := newApplication(logger, configConfig, httpServer)
	return application, nil
}
